import { collection, doc, getDoc, getDocs, limit, orderBy, query, startAfter, where, type DocumentData, type QueryConstraint, type QueryDocumentSnapshot } from 'firebase/firestore';
import { db } from '../firebase';
import { CarListing } from '../types';
const LISTINGS_COLLECTION = 'listings';
const TRUSTED_MEDIA_HOSTS = ['cloudinary.com', 'res.cloudinary.app', 'res.cloudinary.com', 'firebasestorage.googleapis.com', 'storage.googleapis.com'];
const BLOCKED_STOCK_HOSTS = ['images.unsplash.com', 'unsplash.com', 'pexels.com', 'pixabay.com', 'shutterstock.com', 'freepik.com'];
function optionalString(value: unknown): string | undefined { return typeof value === 'string' && value.trim() ? value.trim() : undefined; }
function optionalNumber(value: unknown): number | undefined { if (typeof value === 'number' && Number.isFinite(value)) return value; if (typeof value === 'string' && value.trim()) { const n = Number(value); return Number.isFinite(n) ? n : undefined; } return undefined; }
function optionalBoolean(value: unknown): boolean | undefined { return typeof value === 'boolean' ? value : undefined; }
function optionalStringArray(value: unknown): string[] | undefined { if (!Array.isArray(value)) return undefined; const values = value.filter((x): x is string => typeof x === 'string' && x.trim().length > 0).map(x => x.trim()); return values.length ? values : undefined; }
function isTrustedMediaUrl(value: string): boolean { try { const host = new URL(value).hostname.toLowerCase(); if (BLOCKED_STOCK_HOSTS.some(x => host === x || host.endsWith(`.${x}`))) return false; return TRUSTED_MEDIA_HOSTS.some(x => host === x || host.endsWith(`.${x}`)); } catch { return false; } }
function trustedMedia(value: unknown): string | undefined { const url = optionalString(value); return url && isTrustedMediaUrl(url) ? url : undefined; }
function trustedMediaArray(value: unknown): string[] | undefined { if (!Array.isArray(value)) return undefined; const values = value.map(x => typeof x === 'string' ? trustedMedia(x) : undefined).filter((x): x is string => Boolean(x)); return values.length ? [...new Set(values)] : undefined; }
function isPublished(data: DocumentData): boolean { return data.approved === true && data.isArchived !== true && data.isPaused !== true && data.isSold !== true && data.status !== 'Sold'; }
function timestampMs(value: unknown): number { if (typeof value === 'string') { const ms = Date.parse(value); return Number.isFinite(ms) ? ms : 0; } if (value && typeof value === 'object' && 'toMillis' in value && typeof (value as any).toMillis === 'function') return (value as any).toMillis(); if (typeof value === 'number' && Number.isFinite(value)) return value; return 0; }
export function mapCanonicalListing(id: string, data: DocumentData): CarListing {
  const year = optionalNumber(data.year), price = optionalNumber(data.price), mileage = optionalNumber(data.mileage), engineCC = optionalNumber(data.engineCC);
  const imageUrl = trustedMedia(data.imageUrl); const images = trustedMediaArray(data.images) || (imageUrl ? [imageUrl] : undefined); const primaryImage = trustedMedia(data.primaryImage); const horsepower = optionalString(data.horsepower) || optionalString(data.horspower);
  return { id, title: optionalString(data.title) || '', make: optionalString(data.make) || '', model: optionalString(data.model) || '', year, price, mileage, fuelType: optionalString(data.fuelType) as CarListing['fuelType'], transmission: optionalString(data.transmission) as CarListing['transmission'], imageUrl, verified: optionalBoolean(data.verified), featured: optionalBoolean(data.featured), approved: optionalBoolean(data.approved), dealerId: optionalString(data.dealerId), showroomId: optionalString(data.showroomId), ownerId: optionalString(data.ownerId), description: optionalString(data.description), createdAt: optionalString(data.createdAt), updatedAt: optionalString(data.updatedAt), tags: optionalStringArray(data.tags), specs: { color: optionalString(data.exteriorColor), engineSize: engineCC === undefined ? undefined : `${engineCC} CC`, horsepower, horspower: horsepower, regionalSpecs: optionalString(data.assemblyType) }, createdBy: optionalString(data.createdBy), assignedSalesRepId: optionalString(data.assignedSalesRepId), region: optionalString(data.region), location: optionalString(data.location), phone: optionalString(data.phone), sellerPhone: optionalString(data.sellerPhone), sellerName: optionalString(data.sellerName), sellerWhatsApp: optionalString(data.sellerWhatsApp), sellerType: optionalString(data.sellerType) as CarListing['sellerType'], condition: optionalString(data.condition) as CarListing['condition'], engineCC, exteriorColor: optionalString(data.exteriorColor), bodyCondition: optionalString(data.bodyCondition) as CarListing['bodyCondition'], registrationCity: optionalString(data.registrationCity), documentType: optionalString(data.documentType) as CarListing['documentType'], tokenTaxPaid: optionalBoolean(data.tokenTaxPaid), images, primaryImage, verifiedBadge: optionalBoolean(data.verifiedBadge), assemblyType: optionalString(data.assemblyType) as CarListing['assemblyType'], features: optionalStringArray(data.features), dentPaintDescription: optionalString(data.dentPaintDescription), tokenTaxStatus: optionalString(data.tokenTaxStatus) as CarListing['tokenTaxStatus'], isSold: optionalBoolean(data.isSold), isPaused: optionalBoolean(data.isPaused), isArchived: optionalBoolean(data.isArchived), status: optionalString(data.status) as CarListing['status'], cloudinaryPublicId: optionalString(data.cloudinaryPublicId), cloudinaryPublicIds: optionalStringArray(data.cloudinaryPublicIds), videoUrl: trustedMedia(data.videoUrl), videoCloudinaryPublicId: optionalString(data.videoCloudinaryPublicId), pdfUrl: trustedMedia(data.pdfUrl), pdfCloudinaryPublicId: optionalString(data.pdfCloudinaryPublicId), pdfTitle: optionalString(data.pdfTitle) };
}
export async function fetchListingById(id: string): Promise<CarListing | null> { if (!id.trim()) return null; const snap = await getDoc(doc(db, LISTINGS_COLLECTION, id)); if (!snap.exists() || !isPublished(snap.data())) return null; return mapCanonicalListing(snap.id, snap.data()); }
export interface InventoryPage { listings: CarListing[]; lastVisible: QueryDocumentSnapshot<DocumentData> | null; hasMore: boolean; }
async function fetchPage(constraints: QueryConstraint[], pageSize: number, cursor?: QueryDocumentSnapshot<DocumentData> | null): Promise<InventoryPage> { const q = cursor ? query(collection(db, LISTINGS_COLLECTION), ...constraints, startAfter(cursor)) : query(collection(db, LISTINGS_COLLECTION), ...constraints); const snap = await getDocs(q); const docs = snap.docs; const visibleDocs = docs.filter(d => isPublished(d.data())).slice(0, pageSize); return { listings: visibleDocs.map(d => mapCanonicalListing(d.id, d.data())), lastVisible: visibleDocs.length ? visibleDocs[visibleDocs.length - 1] : null, hasMore: docs.length > pageSize }; }
export async function fetchInventoryPage(pageSize = 24, cursor?: QueryDocumentSnapshot<DocumentData> | null): Promise<InventoryPage> { const safe = Math.min(Math.max(Math.floor(pageSize), 1), 48); try { return await fetchPage([where('approved', '==', true), orderBy('updatedAt', 'desc'), limit(safe + 1)], safe, cursor); } catch (error) { console.warn('[Inventory] updatedAt query unavailable; falling back to createdAt:', error); return fetchPage([where('approved', '==', true), orderBy('createdAt', 'desc'), limit(safe + 1)], safe, cursor); } }
export async function fetchShowroomInventoryPage(showroomId: string, pageSize = 24, cursor?: QueryDocumentSnapshot<DocumentData> | null): Promise<InventoryPage> { const id = showroomId.trim(); if (!id) return { listings: [], lastVisible: null, hasMore: false }; const safe = Math.min(Math.max(Math.floor(pageSize), 1), 48); const run = async (field: 'showroomId' | 'dealerId') => { try { return await fetchPage([where(field, '==', id), where('approved', '==', true), orderBy('updatedAt', 'desc'), limit(safe + 1)], safe, cursor); } catch { try { return await fetchPage([where(field, '==', id), where('approved', '==', true), orderBy('createdAt', 'desc'), limit(safe + 1)], safe, cursor); } catch { return fetchPage([where(field, '==', id), where('approved', '==', true), limit(safe + 1)], safe, cursor); } } }; const [byShowroom, byDealer] = await Promise.all([run('showroomId'), run('dealerId')]); const merged = new Map<string, CarListing>(); [...byShowroom.listings, ...byDealer.listings].forEach(x => merged.set(x.id, x)); const listings = [...merged.values()].sort((a,b) => (timestampMs(b.updatedAt)||timestampMs(b.createdAt))-(timestampMs(a.updatedAt)||timestampMs(a.createdAt))).slice(0, safe); return { listings, lastVisible: null, hasMore: byShowroom.hasMore || byDealer.hasMore }; }
export async function fetchPublishedInventory(): Promise<InventoryPage> { return fetchInventoryPage(24); }
export async function fetchLatestPublishedInventory(pageSize = 48): Promise<CarListing[]> { const safe = Math.min(Math.max(Math.floor(pageSize), 1), 48); const [updated, created] = await Promise.all([fetchPage([where('approved', '==', true), orderBy('updatedAt', 'desc'), limit(safe)], safe).catch(() => null), fetchPage([where('approved', '==', true), orderBy('createdAt', 'desc'), limit(safe)], safe).catch(() => null)]); const merged = new Map<string, CarListing>(); [...(updated?.listings || []), ...(created?.listings || [])].forEach(x => merged.set(x.id, x)); return [...merged.values()].sort((a,b) => (timestampMs(b.updatedAt)||timestampMs(b.createdAt))-(timestampMs(a.updatedAt)||timestampMs(a.createdAt))).slice(0, safe); }
