import React, { useState } from 'react';
import { Camera, FileText, CheckCircle, Download } from 'lucide-react';
import { useAutoSave } from '../../hooks/useAutoSave';
import { jsPDF } from 'jspdf';

export default function InspectionReportGenerator({ vehicleId, onComplete }: { vehicleId?: string; onComplete?: () => void }) {
  const [reportData, setReportData] = useState({ inspectorName:'', vehicleMakeModel:'', vin:'', mileage:'', engineGrading:'good', bodyGrading:'good', suspensionGrading:'good', electronicsGrading:'good', notes:'' });
  const { lastSavedAt } = useAutoSave(`inspection_${vehicleId || 'new'}`, reportData, { delay:1000, onSaveToCloud:async()=>{} });
  const generatePDF=()=>{ const doc=new jsPDF(); doc.setFontSize(18); doc.text('Bazar360 Digital Inspection Report',14,20); doc.setFontSize(12); doc.text(`Inspector: ${reportData.inspectorName}`,14,30); doc.text(`Vehicle: ${reportData.vehicleMakeModel}`,14,37); doc.text(`VIN: ${reportData.vin}`,14,44); doc.text(`Mileage: ${reportData.mileage} km`,14,51); let y=65; [['Engine & Transmission',reportData.engineGrading],['Body & Paint',reportData.bodyGrading],['Suspension & Undercarriage',reportData.suspensionGrading],['Electronics & OBD',reportData.electronicsGrading]].forEach(([a,b])=>{doc.text(a,14,y);doc.text(b,120,y);y+=8;}); if(reportData.notes){y+=5;doc.text('Notes:',14,y);doc.text(doc.splitTextToSize(reportData.notes,180),14,y+7);} doc.save(`inspection_report_${vehicleId||'new'}.pdf`); };
  const color=(s:string)=>s==='good'?'text-emerald-500 bg-emerald-500/10 border-emerald-500/20':s==='fair'?'text-amber-500 bg-amber-500/10 border-amber-500/20':s==='action_required'?'text-rose-500 bg-rose-500/10 border-rose-500/20':'text-slate-500 bg-slate-500/10 border-slate-500/20';
  const Row=({label,field}:{label:string;field:keyof typeof reportData})=><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 p-4 bg-slate-900/50 rounded-xl border border-slate-800"><span className="text-sm font-black uppercase text-slate-300 tracking-wider">{label}</span><div className="flex items-center gap-2">{(['good','fair','action_required'] as const).map(status=><button key={status} onClick={()=>setReportData({...reportData,[field]:status})} className={`px-3 py-2 rounded-lg text-[10px] font-black uppercase tracking-widest border ${reportData[field]===status?color(status):'text-slate-500 border-slate-800'}`}>{status.replace('_',' ')}</button>)}<button type="button" className="p-2 bg-slate-800 text-slate-400 rounded-lg"><Camera size={14}/></button></div></div>;
  return <div className="max-w-3xl mx-auto space-y-6 animate-fade-in pb-20"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-4"><div><h2 className="text-xl font-black uppercase text-sky-400 flex items-center gap-2"><FileText size={20}/>Digital Inspection Report</h2><p className="text-xs text-slate-400 mt-1 uppercase tracking-widest">Bazar360 Certified Health Check</p></div><div className="flex items-center gap-2">{lastSavedAt&&<span className="text-[10px] text-emerald-500 font-mono flex items-center gap-1"><CheckCircle size={10}/>Auto-saved {lastSavedAt.toLocaleTimeString()}</span>}<button onClick={generatePDF} className="px-4 py-2 bg-sky-500 text-slate-950 font-black text-[10px] uppercase rounded-xl flex items-center gap-2"><Download size={14}/>Download PDF</button></div></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{(['inspectorName','vehicleMakeModel','vin','mileage'] as const).map((field)=><input key={field} type="text" placeholder={field==='vehicleMakeModel'?'Vehicle Make & Model':field==='vin'?'VIN / Chassis Number':field==='mileage'?'Mileage (km)':'Inspector Name'} value={reportData[field]} onChange={e=>setReportData({...reportData,[field]:e.target.value})} className="w-full bg-slate-900 border border-slate-800 rounded-xl p-3 text-sm text-white outline-none"/>)}</div><div className="space-y-3"><h3 className="text-sm font-black uppercase text-slate-300 tracking-wider">Checklist & Grading</h3><Row label="Engine & Transmission" field="engineGrading"/><Row label="Body & Paint" field="bodyGrading"/><Row label="Suspension & Undercarriage" field="suspensionGrading"/><Row label="Electronics & OBD" field="electronicsGrading"/></div><textarea placeholder="Add specific remarks or findings..." value={reportData.notes} onChange={e=>setReportData({...reportData,notes:e.target.value})} className="w-full bg-slate-900 border border-slate-800 rounded-xl p-3 text-sm text-white h-24 resize-none"/><button onClick={onComplete} className="w-full py-3.5 bg-emerald-500 text-slate-950 font-black text-sm uppercase tracking-widest rounded-xl">Finalize & Submit Report</button></div>;
}
