import { CarListing, Dealer } from './types';

export const INITIAL_DEALERS: Dealer[] = [
  {
    id: 'auto-choice-peshawar',
    name: 'Auto Choice - The Right Choice',
    subtitle: 'The Right Choice | To buy and Sell New and Used Cars, Jeeps and SUVs',
    location: 'Alamas Car Village, Ring Road, Peshawar',
    rating: 4.9,
    vehiclesCount: 6,
    followersCount: '5.6k',
    avatarLetter: 'AC',
    avatarUrl: 'https://res.cloudinary.com/me634xd0/image/upload/v1786719980/bazar360_showroom_logos/gvp4jqzmccmzezbuxkdg.jpg',
    logo: 'https://res.cloudinary.com/me634xd0/image/upload/v1786719980/bazar360_showroom_logos/gvp4jqzmccmzezbuxkdg.jpg',
    logoUrl: 'https://res.cloudinary.com/me634xd0/image/upload/v1786719980/bazar360_showroom_logos/gvp4jqzmccmzezbuxkdg.jpg',
    coverImage: 'https://res.cloudinary.com/me634xd0/image/upload/v1786266378/bazar360_covers/i9rknevddargoerv3xsq.jpg',
    phone: '+923159085086',
    whatsapp: '923159085086',
    description: 'Auto Choice is a premier automotive marketplace specialized in buying and selling immaculate new and used cars, robust jeeps, and luxury premium SUVs. Committed to absolute transparency, nationwide delivery, and personalized customer service all over Pakistan.',
    socials: {
      instagram: 'https://instagram.com/autochoice',
      tiktok: 'https://www.tiktok.com/@grandautochoice',
      website: 'https://bazar360.online/dealers/auto-choice-peshawar',
    },
    smartSlug: 'AutoChoice01',
    passkey: 'Choice360',
    isPrivateLocked: false,
    customSmartUrl: 'bazar360.online/AutoChoice01',
    activityFeed: [],
    teamMembers: [
      {
        id: 'tm-1',
        name: 'Malak Mazhar',
        title: 'Showroom Partner / Services Lead',
        phone: '+923159085086',
        whatsapp: '923159085086',
        email: 'Mazharsouls@gmail.com',
        active: true,
      },
      {
        id: 'tm-3',
        name: 'M. Nasir Mirza',
        title: 'Chief Sales Executive',
        phone: '+923005908508',
        whatsapp: '923005908508',
      },
      {
        id: 'tm-4',
        name: 'Asfandyar Zafar',
        title: 'Fleet & Trade Manager',
        phone: '+923129085033',
        whatsapp: '923129085033',
      },
    ],
  },
];

export const INITIAL_LISTINGS: CarListing[] = [
  {
    id: 'listing-fortuner-legender-2023',
    title: 'Toyota Fortuner Legender 2.8 4x4',
    make: 'Toyota',
    model: 'Fortuner',
    variant: 'Legender 2.8 Sigma 4',
    vehicleType: 'SUVs',
    year: 2023,
    price: 19850000, // PKR 1.985 Crore
    mileage: 18500,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    imageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    primaryImage: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
    ],
    verified: true,
    verifiedBadge: true,
    featured: true,
    approved: true,
    condition: 'Used',
    engineCC: 2800,
    exteriorColor: 'Super White / Black Roof',
    bodyCondition: 'Total Genuine',
    registrationCity: 'Islamabad',
    documentType: 'Smart Card',
    tokenTaxPaid: true,
    tokenTaxStatus: 'Paid',
    assemblyType: 'Local',
    dealerId: 'auto-choice-peshawar',
    sellerType: 'Showroom',
    sellerName: 'Auto Choice Peshawar',
    sellerPhone: '+923159085086',
    sellerWhatsApp: '923159085086',
    location: 'Alamas Car Village, Ring Road, Peshawar',
    region: 'Khyber Pakhtunkhwa',
    createdAt: '2026-08-20T10:00:00.000Z',
    description: 'Immaculate bumper-to-bumper genuine condition Toyota Fortuner Legender 2023. Dual tone pearl white with black roof, JBL premium sound system, ventilated powered seats, 200+ point verified inspection clear.',
    tags: ['4x4', 'SUV', 'Legender', 'Diesel', 'Verified'],
    specs: {
      color: 'Super White',
      engineSize: '2.8L D-4D',
      horspower: '201 hp',
      regionalSpecs: 'Pakistani',
    },
    status: 'Available',
  },
  {
    id: 'listing-civic-rs-2022',
    title: 'Honda Civic RS 1.5 Turbo LL-CVT',
    make: 'Honda',
    model: 'Civic',
    variant: 'RS Turbo',
    vehicleType: 'Sedans',
    year: 2022,
    price: 9250000, // PKR 92.5 Lakh
    mileage: 24000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
    primaryImage: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
    ],
    verified: true,
    verifiedBadge: true,
    featured: true,
    approved: true,
    condition: 'Used',
    engineCC: 1500,
    exteriorColor: 'Meteoroid Gray Metallic',
    bodyCondition: 'Total Genuine',
    registrationCity: 'Lahore',
    documentType: 'Smart Card',
    tokenTaxPaid: true,
    tokenTaxStatus: 'Paid',
    assemblyType: 'Local',
    dealerId: 'auto-choice-peshawar',
    sellerType: 'Showroom',
    sellerName: 'Auto Choice Peshawar',
    sellerPhone: '+923159085086',
    sellerWhatsApp: '923159085086',
    location: 'Alamas Car Village, Ring Road, Peshawar',
    region: 'Khyber Pakhtunkhwa',
    createdAt: '2026-08-19T14:30:00.000Z',
    description: 'Honda Civic RS Turbo 11th Gen in stunning Meteoroid Gray. Honda Sensing active safety package, electric sunroof, paddle shifters, ambient cockpit lighting. 100% genuine guaranteed.',
    tags: ['Sedan', 'Turbo', 'Civic RS', 'Verified'],
    specs: {
      color: 'Meteoroid Gray',
      engineSize: '1.5L VTEC Turbo',
      horspower: '176 hp',
      regionalSpecs: 'Pakistani',
    },
    status: 'Available',
  },
  {
    id: 'listing-sportage-awd-2023',
    title: 'KIA Sportage AWD 2.0',
    make: 'KIA',
    model: 'Sportage',
    variant: 'AWD 2.0L',
    vehicleType: 'SUVs',
    year: 2023,
    price: 7850000, // PKR 78.5 Lakh
    mileage: 29000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80',
    primaryImage: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80',
    ],
    verified: true,
    verifiedBadge: true,
    featured: false,
    approved: true,
    condition: 'Used',
    engineCC: 2000,
    exteriorColor: 'Panthera Metal',
    bodyCondition: 'Total Genuine',
    registrationCity: 'Islamabad',
    documentType: 'Smart Card',
    tokenTaxPaid: true,
    tokenTaxStatus: 'Paid',
    assemblyType: 'Local',
    dealerId: 'auto-choice-peshawar',
    sellerType: 'Showroom',
    sellerName: 'Auto Choice Peshawar',
    sellerPhone: '+923159085086',
    sellerWhatsApp: '923159085086',
    location: 'Alamas Car Village, Ring Road, Peshawar',
    region: 'Khyber Pakhtunkhwa',
    createdAt: '2026-08-18T11:20:00.000Z',
    description: 'All-Wheel Drive KIA Sportage 2.0L in top-notch mechanical and aesthetic condition. Panoramic roof, electronic parking brake, wireless phone charging, 200+ point verified inspection pass.',
    tags: ['SUV', 'AWD', 'KIA', 'Verified'],
    specs: {
      color: 'Panthera Metal',
      engineSize: '2.0L MPI',
      horspower: '155 hp',
      regionalSpecs: 'Pakistani',
    },
    status: 'Available',
  },
  {
    id: 'listing-yaris-ativ-x-2023',
    title: 'Toyota Yaris ATIV X CVT 1.5',
    make: 'Toyota',
    model: 'Yaris',
    variant: 'ATIV X 1.5 CVT',
    vehicleType: 'Sedans',
    year: 2023,
    price: 5850000, // PKR 58.5 Lakh
    mileage: 21000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    imageUrl: 'https://images.unsplash.com/photo-1590362891988-f778047831d6?auto=format&fit=crop&w=1200&q=80',
    primaryImage: 'https://images.unsplash.com/photo-1590362891988-f778047831d6?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1590362891988-f778047831d6?auto=format&fit=crop&w=1200&q=80',
    ],
    verified: true,
    verifiedBadge: true,
    featured: false,
    approved: true,
    condition: 'Used',
    engineCC: 1500,
    exteriorColor: 'Silver Metallic',
    bodyCondition: 'Total Genuine',
    registrationCity: 'Peshawar',
    documentType: 'Smart Card',
    tokenTaxPaid: true,
    tokenTaxStatus: 'Paid',
    assemblyType: 'Local',
    dealerId: 'auto-choice-peshawar',
    sellerType: 'Showroom',
    sellerName: 'Auto Choice Peshawar',
    sellerPhone: '+923159085086',
    sellerWhatsApp: '923159085086',
    location: 'Alamas Car Village, Ring Road, Peshawar',
    region: 'Khyber Pakhtunkhwa',
    createdAt: '2026-08-17T09:15:00.000Z',
    description: 'Toyota Yaris ATIV X top of the line 1.5L. Excellent fuel economy (16-18 km/l), push start, climate control, multimedia steering. Driven carefully within city limits.',
    tags: ['Sedan', 'Toyota', 'Yaris', 'Verified'],
    specs: {
      color: 'Silver Metallic',
      engineSize: '1.5L Dual VVT-i',
      horspower: '106 hp',
      regionalSpecs: 'Pakistani',
    },
    status: 'Available',
  },
  {
    id: 'listing-alto-vxl-2024',
    title: 'Suzuki Alto VXL AGS 660cc',
    make: 'Suzuki',
    model: 'Alto',
    variant: 'VXL AGS',
    vehicleType: 'Sedans',
    year: 2024,
    price: 3150000, // PKR 31.5 Lakh
    mileage: 8200,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    imageUrl: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80',
    primaryImage: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80',
    ],
    verified: true,
    verifiedBadge: true,
    featured: false,
    approved: true,
    condition: 'Used',
    engineCC: 660,
    exteriorColor: 'Solid White',
    bodyCondition: 'Total Genuine',
    registrationCity: 'Islamabad',
    documentType: 'Smart Card',
    tokenTaxPaid: true,
    tokenTaxStatus: 'Paid',
    assemblyType: 'Local',
    dealerId: 'auto-choice-peshawar',
    sellerType: 'Showroom',
    sellerName: 'Auto Choice Peshawar',
    sellerPhone: '+923159085086',
    sellerWhatsApp: '923159085086',
    location: 'Alamas Car Village, Ring Road, Peshawar',
    region: 'Khyber Pakhtunkhwa',
    createdAt: '2026-08-16T12:00:00.000Z',
    description: 'Brand new like Suzuki Alto VXL AGS 2024. First owner, dual airbags, ABS brakes, touch display screen with reverse camera. Ultra economical daily runner.',
    tags: ['Hatchback', 'Suzuki', 'Alto', 'Economical'],
    specs: {
      color: 'Solid White',
      engineSize: '658cc R06A',
      horspower: '39 hp',
      regionalSpecs: 'Pakistani',
    },
    status: 'Available',
  },
];
